version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ./docker-entrypoint.sh
    env_file:
      - ./.env
    container_name: backend
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
  #resume:
   # build: ./my_cv
   # container_name: resume

volumes:
  postgres_data:
  static:

networks:
  default:
    external:
      name: docker_host
