# Generated by Django 4.0 on 2021-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['blog_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='no slug', upload_to='blog/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
