# Generated by Django 4.0 on 2021-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='received_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
