# Generated by Django 4.0 on 2022-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
